name: NMLEnergySystem
version: '1.0'
main: io.github.NoOne.nMLEnergySystem.NMLEnergySystem
api-version: '1.21.8'
depend:
  - NMLPlayerStats
description: Plugin for No Man's Land to manage the player's energy
